name: Build baas-client
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

# allow only one concurrent build
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  prepare:
    name: Prepare build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Get next version
        uses: reecetech/version-increment@2023.10.2
        id: version
        with:
          scheme: "calver"
          increment: "patch"
          use_api: "true"

  build:
    name: Build and release baas-client
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - name: build and tag library release
        shell: bash
        env:
          VERSION: ${{ needs.prepare.outputs.version }}
        run: |-
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/integrail/baas-client.git
          bash <(curl -Ls "https://welder.simple-container.com/welder.sh") make --timestamps
          bash <(curl -Ls "https://welder.simple-container.com/welder.sh") deploy -e prod --timestamps